# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zabulskyy/UCU/OperatingSystems/myshell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zabulskyy/UCU/OperatingSystems/myshell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zabulskyy/UCU/OperatingSystems/myshell/CMakeFiles /home/zabulskyy/UCU/OperatingSystems/myshell/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zabulskyy/UCU/OperatingSystems/myshell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named myls

# Build rule for target.
myls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myls
.PHONY : myls

# fast build rule for target.
myls/fast:
	$(MAKE) -f CMakeFiles/myls.dir/build.make CMakeFiles/myls.dir/build
.PHONY : myls/fast

#=============================================================================
# Target rules for targets named myshell

# Build rule for target.
myshell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myshell
.PHONY : myshell

# fast build rule for target.
myshell/fast:
	$(MAKE) -f CMakeFiles/myshell.dir/build.make CMakeFiles/myshell.dir/build
.PHONY : myshell/fast

#=============================================================================
# Target rules for targets named myrm

# Build rule for target.
myrm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myrm
.PHONY : myrm

# fast build rule for target.
myrm/fast:
	$(MAKE) -f CMakeFiles/myrm.dir/build.make CMakeFiles/myrm.dir/build
.PHONY : myrm/fast

#=============================================================================
# Target rules for targets named mycat

# Build rule for target.
mycat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mycat
.PHONY : mycat

# fast build rule for target.
mycat/fast:
	$(MAKE) -f CMakeFiles/mycat.dir/build.make CMakeFiles/mycat.dir/build
.PHONY : mycat/fast

#=============================================================================
# Target rules for targets named myhello

# Build rule for target.
myhello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 myhello
.PHONY : myhello

# fast build rule for target.
myhello/fast:
	$(MAKE) -f CMakeFiles/myhello.dir/build.make CMakeFiles/myhello.dir/build
.PHONY : myhello/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/myshell.dir/build.make CMakeFiles/myshell.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/myshell.dir/build.make CMakeFiles/myshell.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/myshell.dir/build.make CMakeFiles/myshell.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mycat.o: src/mycat.cpp.o

.PHONY : src/mycat.o

# target to build an object file
src/mycat.cpp.o:
	$(MAKE) -f CMakeFiles/mycat.dir/build.make CMakeFiles/mycat.dir/src/mycat.cpp.o
.PHONY : src/mycat.cpp.o

src/mycat.i: src/mycat.cpp.i

.PHONY : src/mycat.i

# target to preprocess a source file
src/mycat.cpp.i:
	$(MAKE) -f CMakeFiles/mycat.dir/build.make CMakeFiles/mycat.dir/src/mycat.cpp.i
.PHONY : src/mycat.cpp.i

src/mycat.s: src/mycat.cpp.s

.PHONY : src/mycat.s

# target to generate assembly for a file
src/mycat.cpp.s:
	$(MAKE) -f CMakeFiles/mycat.dir/build.make CMakeFiles/mycat.dir/src/mycat.cpp.s
.PHONY : src/mycat.cpp.s

src/myhello.o: src/myhello.cpp.o

.PHONY : src/myhello.o

# target to build an object file
src/myhello.cpp.o:
	$(MAKE) -f CMakeFiles/myhello.dir/build.make CMakeFiles/myhello.dir/src/myhello.cpp.o
.PHONY : src/myhello.cpp.o

src/myhello.i: src/myhello.cpp.i

.PHONY : src/myhello.i

# target to preprocess a source file
src/myhello.cpp.i:
	$(MAKE) -f CMakeFiles/myhello.dir/build.make CMakeFiles/myhello.dir/src/myhello.cpp.i
.PHONY : src/myhello.cpp.i

src/myhello.s: src/myhello.cpp.s

.PHONY : src/myhello.s

# target to generate assembly for a file
src/myhello.cpp.s:
	$(MAKE) -f CMakeFiles/myhello.dir/build.make CMakeFiles/myhello.dir/src/myhello.cpp.s
.PHONY : src/myhello.cpp.s

src/myls.o: src/myls.cpp.o

.PHONY : src/myls.o

# target to build an object file
src/myls.cpp.o:
	$(MAKE) -f CMakeFiles/myls.dir/build.make CMakeFiles/myls.dir/src/myls.cpp.o
.PHONY : src/myls.cpp.o

src/myls.i: src/myls.cpp.i

.PHONY : src/myls.i

# target to preprocess a source file
src/myls.cpp.i:
	$(MAKE) -f CMakeFiles/myls.dir/build.make CMakeFiles/myls.dir/src/myls.cpp.i
.PHONY : src/myls.cpp.i

src/myls.s: src/myls.cpp.s

.PHONY : src/myls.s

# target to generate assembly for a file
src/myls.cpp.s:
	$(MAKE) -f CMakeFiles/myls.dir/build.make CMakeFiles/myls.dir/src/myls.cpp.s
.PHONY : src/myls.cpp.s

src/myrm.o: src/myrm.cpp.o

.PHONY : src/myrm.o

# target to build an object file
src/myrm.cpp.o:
	$(MAKE) -f CMakeFiles/myrm.dir/build.make CMakeFiles/myrm.dir/src/myrm.cpp.o
.PHONY : src/myrm.cpp.o

src/myrm.i: src/myrm.cpp.i

.PHONY : src/myrm.i

# target to preprocess a source file
src/myrm.cpp.i:
	$(MAKE) -f CMakeFiles/myrm.dir/build.make CMakeFiles/myrm.dir/src/myrm.cpp.i
.PHONY : src/myrm.cpp.i

src/myrm.s: src/myrm.cpp.s

.PHONY : src/myrm.s

# target to generate assembly for a file
src/myrm.cpp.s:
	$(MAKE) -f CMakeFiles/myrm.dir/build.make CMakeFiles/myrm.dir/src/myrm.cpp.s
.PHONY : src/myrm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... myls"
	@echo "... rebuild_cache"
	@echo "... myshell"
	@echo "... myrm"
	@echo "... mycat"
	@echo "... edit_cache"
	@echo "... myhello"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mycat.o"
	@echo "... src/mycat.i"
	@echo "... src/mycat.s"
	@echo "... src/myhello.o"
	@echo "... src/myhello.i"
	@echo "... src/myhello.s"
	@echo "... src/myls.o"
	@echo "... src/myls.i"
	@echo "... src/myls.s"
	@echo "... src/myrm.o"
	@echo "... src/myrm.i"
	@echo "... src/myrm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

